.gitignore, bootstrap.php, composer.json, composer.lock, includes/RestApi/AISearchController.php, includes/SiteGen/SiteGen.php
Added functions to be used for generating site content, structures etc.
=> add all api wrappers for generating content

includes/SiteGen/SiteGen.php
Each of the sitegen object keys will be saved as a separate option now eg: "nfd-ai-site-gen-pluginrecommendation", "nfd-ai-site-gen-contentbrief"
=> saving sitegen object values in different options

includes/SiteGen/SiteGen.php, includes/Utils/AISearchUtil.php, includes/Utils/PatternParser.php
Switches the parser to PHP and does the content replace using JSON parsed objects.
=> parse on php and replace pattern as json

includes/SiteGen/SiteGen.php
While looping through the patterns the homepage content was getting overridden instead of getting appended.
=> fixing homepage content

includes/SiteGen/SiteGen.php, includes/Utils/AISearchUtil.php
Please check if this makes sense.
=> Check `hasAISiteGen`, deprecate `canAccessAI`

composer.json, composer.lock
Update the data module version that was exiting the lint checks.
=> Fix PHP Lint

includes/Utils/AISearchUtil.php
=> Fix Error inconsistencies

includes/Patterns.php, includes/SiteGen/SiteGen.php
=> Use custom menu patterns for menu pages in the AI Sitegen flow

includes/SiteGen/SiteGen.php
=> Generate Site Posts for Bloggers and Writers

includes/SiteGen/SiteGen.php
- Adds a check to make sure that we can use same category pattern multiple times on a page.
- Moves back to using randomisation for selecting the patterns both in first and subsequent regenerate passes but ensures that the home pages being generated all have unique hero patterns in a given pass so that we do not have the pattern repeated.
- Will need the fixed content structure and the changes that include the pattern slug in generated patterns to go live before this PR sees the light of the day.
=> make patterns reusable

composer.json, composer.lock
Bumping wp-module-installer to the latest version
=> bump version for wp-module-installer

includes/Patterns.php, includes/SiteGen/SiteGen.php
=> Add Custom WP Grammar to sample posts

includes/SiteGen/SiteGen.php
Adds a step to call an API to refine the site description before using it further, saves the refined site description for re-use.
Example, the following prompt:
Welcome to Massage Haven - Your Oasis of Relaxation and Renewal. Bienvenido a Massage Haven, tu refugio de tranquilidad y bienestar. We offer a diverse range of therapeutic massages designed to help you disconnect from daily stress and reconnect with your inner peace. Our mission is to not only provide physical relief but to offer a space for mental and spiritual rejuvenation. At Massage Haven, we believe in the power of touch as a pathway to health and balance. Our experienced therapists are trained in various massage techniques to meet individual needs and wellness goals. Whether you seek relaxation, pain relief, or emotional …
=> add step to refine the site description before proceeding further

includes/SiteGen/SiteGen.php
Only add comma between values to avoid trailing slash.
=> Avoid trailing slash

bootstrap.php, includes/SiteGen/SiteGen.php
Point the page generation endpoint to the new service location.
=> Point page content generation service to new location

bootstrap.php, includes/SiteGen/SiteGen.php
Probably won't be needed until the migration but this should match how we pass the token in other repos.
=> Pass service token as part of the header instead of body

bootstrap.php, includes/SiteGen/SiteGen.php
This PR adds the locale param to support multi-lingual content generation.
=> Multilingual support

includes/SiteGen/SiteGen.php
In terms of feature delivery, Sitekits are mostly independent of the AI module. So this PR only does 2 things:
- Remove `content_style` parameter requirement in `keywords` call. [See this  Onboarding-Data PR for more info](https://github.com/newfold-labs/wp-module-onboarding-data/pull/159)
- Expose `get_refined_site_description` method: nothing seems sensitive about this method, and making it public will help us migrate away from this module in terms of Onboarding usage.
=> Sitekits Support: Make get_refined_site_description method public

languages/wp-module-ai-de_DE.po, languages/wp-module-ai-en_AU.po, languages/wp-module-ai-en_GB.po, languages/wp-module-ai-es_ES.po, languages/wp-module-ai-es_MX.po, languages/wp-module-ai-fr_FR.po, languages/wp-module-ai-it_IT.po, languages/wp-module-ai-nl_NL.po, languages/wp-module-ai-pt_BR.po, languages/wp-module-ai.pot
This PR updates the i18n translation files.
=> Update i18n translation files

includes/SiteGen/SiteGen.php
Currently the site pages content requests are dispatched in a foreach loop... so each page has to have its request sent through the network, receive and processed the response, add content to the results array, then move on to the next page. This design is adding a significant delay to the overall SiteGen time. Here are some timings i capture during testing:
- 16s
- 23s
- 17s
- 24s
- 20s
- 21s
This PR sends the request using `\WpOrg\Requests\Requests::request_multiple` which can dispatch multiple external network requests in parallel and process them in parallel if its `complete` callback option is hooked into which we're doing in this PR. Here some timings as a result of this PR:
- 6s
- 7s
- 7s
- 5s
- 6s
- 5s
These results are more in-line with what we see on the Service side where a …
=> Request site pages content in parallel
